### ISSUE TITLE
Need to supply a transaction id is inconsistent between playground and CLI/REST API

### ISSUE THREAD

**Issue by davidkel** [fabric-composer/fabric-composer#538]
## Context
When using the playground it hides the identifier of a transaction and provides a unique value using uuid.v4().
In the case of the CLI and the REST Api, if you supply transaction JSON without defining a transaction identifier value it gets rejected. In the case of the CLI the error returned is 
```
Error: Invalid or missing identifier for Type OwnerCreationTransaction in namespace com.namespace.model
    at Factory.newResource (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/factory.js:89:19)
    at Serializer.fromJSON (/usr/local/lib/node_modules/composer-cli/node_modules/composer-common/lib/serializer.js:141:37)
    at then.then.e (/usr/local/lib/node_modules/composer-cli/lib/cmds/transaction/lib/submit.js:83:39)
Command failed.
```

We should have consistency here and I believe the right approach might be
If transaction id provided use that, otherwise generate a unique one and use that rather than throw an error.

**Comment by nklincoln** [comment]
It would appear that Simon has already made some edits that will fix this issue within serializer.js (fromJson) by conditionally creating a new resource, that will internally provide an identifier if not already present.

**Comment by nklincoln** [comment]
The composer playground now contains some redundant code as a result of the above change and so should be edited to account for the above changes. Proposal:

- do not supply any uuid or date on transaction submission
- use specific newTransaction method in the factory to generate a transaction in the UI

Above will permit the reduction in code lines, which is always nice :)

**Comment by nklincoln** [comment]
fixed upstream and tided up with #632

**Comment by himanimukne** [comment]
ven after writing `"transactionId" : true` or `"transactionId" : false`, the problem persists.

Another user on stackoverflow had encountered a similar problem. They fixed it by making their npm and node.js non-root. In my case, it is already non-root. [non-root](https://i.stack.imgur.com/0DWCv.png)
Is it possible that npm and node.js are not installed properly? I had received a few errors during its installation npm errors during installation
[npm installation errors](https://i.stack.imgur.com/RzvKv.png)
